#!/usr/bin/env python3
"""Validate ADR frontmatter and generate docs/decisions/INDEX.md."""

import re
import sys
from pathlib import Path

import yaml

DECISIONS_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent / "docs" / "decisions"
INDEX_PATH = DECISIONS_DIR / "INDEX.md"
FILENAME_RE = re.compile(r"^ADR-(\d{3})-[\w-]+\.md$")
VALID_STATUSES = {"draft", "accepted"}
REQUIRED_FIELDS = ("title", "description", "status", "tags")
REQUIRED_SECTIONS = ("Context", "Decision", "Consequences")


def parse_frontmatter(path: Path) -> dict | None:
    """Extract YAML frontmatter from a file. Returns None if no frontmatter."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("---", 3)
    if end == -1:
        return None
    raw = text[3:end]
    return yaml.safe_load(raw)


def validate_adrs(adr_files: list[Path]) -> tuple[list[dict], list[str], list[str]]:
    """Validate all ADR files. Returns (parsed entries, errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []
    entries: list[dict] = []

    for path in adr_files:
        name = path.name
        match = FILENAME_RE.match(name)
        if not match:
            errors.append(f"ERROR [{name}]: Filename doesn't match ADR-NNN-slug.md pattern")
            continue

        number = int(match.group(1))
        fm = parse_frontmatter(path)

        if fm is None:
            errors.append(f"ERROR [{name}]: Missing YAML frontmatter entirely")
            continue

        file_errors = False
        for field in REQUIRED_FIELDS:
            if not fm.get(field):
                errors.append(f"ERROR [{name}]: Missing required field: {field}")
                file_errors = True

        status = fm.get("status", "")
        if status == "draft":
            errors.append(f"ERROR [{name}]: status is 'draft' (signals incomplete work)")
            file_errors = True
        elif status and status not in VALID_STATUSES:
            errors.append(f"ERROR [{name}]: Unrecognized status '{status}' (expected 'draft' or 'accepted')")
            file_errors = True

        # Check required body sections
        text = path.read_text(encoding="utf-8")
        body = text.split("---", 2)[-1] if text.startswith("---") else text
        for section in REQUIRED_SECTIONS:
            if not re.search(rf"^#{{1,6}}\s+{section}\b", body, re.MULTILINE):
                errors.append(f"ERROR [{name}]: Missing required section: {section}")
                file_errors = True

        if not file_errors:
            entries.append(
                {
                    "number": number,
                    "filename": name,
                    "title": fm["title"],
                    "description": fm["description"],
                    "status": fm["status"],
                    "tags": ", ".join(fm.get("tags", [])),
                }
            )

    return entries, errors, warnings


def generate_index(entries: list[dict]) -> str:
    """Generate INDEX.md content from validated entries."""
    entries.sort(key=lambda e: e["number"])

    lines = [
        "<!-- AUTO-GENERATED by .claude/skills/adr/scripts/generate_index.py — do not edit manually -->",
        "",
        "# Architecture Decision Records",
        "",
        "| Number | Title | Description | Status | Tags |",
        "|--------|-------|-------------|--------|------|",
    ]

    for e in entries:
        num = f"ADR-{e['number']:03d}"
        link = f"[{num}]({e['filename']})"
        lines.append(f"| {link} | {e['title']} | {e['description']} | {e['status']} | {e['tags']} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not DECISIONS_DIR.is_dir():
        print(f"ERROR: Directory not found: {DECISIONS_DIR}", file=sys.stderr)
        return 1

    adr_files = sorted(DECISIONS_DIR.glob("ADR-*.md"))
    if not adr_files:
        print("No ADR files found.", file=sys.stderr)
        return 1

    entries, errors, warnings = validate_adrs(adr_files)

    for w in warnings:
        print(w, file=sys.stderr)
    for e in errors:
        print(e, file=sys.stderr)

    if errors:
        print(f"\n{len(errors)} error(s) found. Fix them before INDEX.md can be generated.", file=sys.stderr)
        return 1

    index_content = generate_index(entries)

    # --check verifies the committed index without writing, for CI. Done here rather
    # than by regenerating and diffing with git, because the image this runs in is a
    # Python toolchain and carries no git -- and adding one to compare two strings
    # would be an unpinned apt package in the supply chain for no gain.
    if "--check" in sys.argv[1:]:
        committed = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.is_file() else None
        if committed != index_content:
            print(
                f"ERROR: {INDEX_PATH} is out of date with the ADR frontmatter.\n"
                f"Run `task adr-index` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{INDEX_PATH} is up to date ({len(entries)} entries).")
        return 0

    INDEX_PATH.write_text(index_content, encoding="utf-8")
    print(f"Generated {INDEX_PATH} with {len(entries)} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
